import type {
  AgentLead,
  AppealCase,
  Campaign,
  DiscoverySource,
  EvidenceAsset,
  PartnerAgent,
  ReputationRecord,
  RiskCase,
  VerificationRecord,
} from "./domain.js";
import type { SeedData } from "./seed.js";

const discoverySources = [
  {
    sourceId: "src_demo_registry",
    sourceType: "public_registry",
    name: "Global Buyer Agent Registry",
    baseUrl: "https://registry.lumio.ai",
    seedUrls: ["https://registry.lumio.ai/agents"],
    active: true,
    crawlPolicy: { rateLimit: 1, maxDepth: 1 },
    verticalHints: ["crm_software", "sales_ops", "saas_procurement"],
    geoHints: ["US", "EU", "APAC"],
    createdAt: "2026-03-01T08:00:00.000Z",
    updatedAt: "2026-03-11T08:00:00.000Z",
  },
  {
    sourceId: "src_demo_directory",
    sourceType: "partner_directory",
    name: "Enterprise Partner Directory",
    baseUrl: "https://directory.lumio.ai",
    seedUrls: ["https://directory.lumio.ai/partners"],
    active: true,
    crawlPolicy: { rateLimit: 1, maxDepth: 1 },
    verticalHints: ["crm_software", "revops", "workflow_automation"],
    geoHints: ["US", "EU", "SG"],
    createdAt: "2026-03-01T08:30:00.000Z",
    updatedAt: "2026-03-11T08:30:00.000Z",
  },
];

const leads = [
  {
    agentId: "lead_demo_northstar",
    dataOrigin: "seed",
    dataProvenance: "demo_seed",
    source: "demo_registry",
    sourceType: "public_registry",
    sourceRef: "demo:northstar",
    providerOrg: "Northstar Procurement Desk",
    cardUrl: "https://registry.lumio.ai/agents/northstar",
    verticals: ["crm_software", "saas_procurement"],
    skills: ["compare_and_shortlist", "vendor_discovery"],
    geo: ["UK", "EU"],
    authModes: ["oauth2", "api_key"],
    acceptsSponsored: true,
    supportsDisclosure: true,
    supportsDeliveryReceipt: true,
    supportsPresentationReceipt: true,
    trustSeed: 0.9,
    leadScore: 0.91,
    discoveredAt: "2026-03-02T09:00:00.000Z",
    lastSeenAt: "2026-03-11T09:00:00.000Z",
    endpointUrl: "https://registry.lumio.ai/agents/northstar/opportunities",
    contactRef: "ops@northstarcrm.ai",
    missingFields: [],
    reachProxy: 0.88,
    monetizationReadiness: 0.9,
    verificationStatus: "active",
    lastVerifiedAt: "2026-03-11T08:00:00.000Z",
    verificationOwner: "ops:alice",
    evidenceRef: "asset_demo_northstar_case",
    assignedOwner: "ops:alice",
    notes: "High-fit EU enterprise buying desk used in demos.",
    dedupeKey: "northstar_procurement_desk_demo_registry",
    scoreBreakdown: { icpFit: 0.94, protocolFit: 0.9, reachFit: 0.88 },
  },
  {
    agentId: "lead_demo_summit",
    dataOrigin: "seed",
    dataProvenance: "demo_seed",
    source: "demo_directory",
    sourceType: "partner_directory",
    sourceRef: "demo:summit",
    providerOrg: "Summit RevOps Agent",
    cardUrl: "https://directory.lumio.ai/partners/summit",
    verticals: ["crm_software", "revops"],
    skills: ["compare_and_shortlist", "pricing_analysis"],
    geo: ["US", "EU"],
    authModes: ["oauth2"],
    acceptsSponsored: true,
    supportsDisclosure: true,
    supportsDeliveryReceipt: true,
    supportsPresentationReceipt: true,
    trustSeed: 0.84,
    leadScore: 0.86,
    discoveredAt: "2026-03-03T09:00:00.000Z",
    lastSeenAt: "2026-03-11T09:00:00.000Z",
    endpointUrl: "https://directory.lumio.ai/partners/summit/opportunities",
    contactRef: "alliances@summitrevops.ai",
    missingFields: [],
    reachProxy: 0.82,
    monetizationReadiness: 0.84,
    verificationStatus: "active",
    lastVerifiedAt: "2026-03-11T08:10:00.000Z",
    verificationOwner: "ops:bob",
    evidenceRef: "asset_demo_northstar_case",
    assignedOwner: "ops:bob",
    notes: "Balanced mid-market coverage and clean disclosure handling.",
    dedupeKey: "summit_revops_agent_demo_directory",
    scoreBreakdown: { icpFit: 0.88, protocolFit: 0.82, reachFit: 0.82 },
  },
  {
    agentId: "lead_demo_vector",
    dataOrigin: "seed",
    dataProvenance: "demo_seed",
    source: "demo_registry",
    sourceType: "public_registry",
    sourceRef: "demo:vector",
    providerOrg: "Vector Workspace Agent",
    cardUrl: "https://registry.lumio.ai/agents/vector",
    verticals: ["crm_software", "workflow_automation"],
    skills: ["vendor_discovery", "pricing_analysis"],
    geo: ["US", "CA"],
    authModes: ["oauth2", "api_key"],
    acceptsSponsored: true,
    supportsDisclosure: true,
    supportsDeliveryReceipt: true,
    supportsPresentationReceipt: false,
    trustSeed: 0.83,
    leadScore: 0.85,
    discoveredAt: "2026-03-03T12:00:00.000Z",
    lastSeenAt: "2026-03-11T09:30:00.000Z",
    endpointUrl: "https://registry.lumio.ai/agents/vector/opportunities",
    contactRef: "growth@vectorworkspace.ai",
    missingFields: ["supportsPresentationReceipt"],
    reachProxy: 0.8,
    monetizationReadiness: 0.83,
    verificationStatus: "active",
    lastVerifiedAt: "2026-03-10T16:00:00.000Z",
    verificationOwner: "ops:alice",
    evidenceRef: "https://registry.lumio.ai/agents/vector/proof",
    assignedOwner: "ops:alice",
    notes: "Strong North America fit with clean API operations.",
    dedupeKey: "vector_workspace_agent_demo_registry",
    scoreBreakdown: { icpFit: 0.86, protocolFit: 0.84, reachFit: 0.8 },
  },
  {
    agentId: "lead_demo_orbit",
    dataOrigin: "seed",
    dataProvenance: "demo_seed",
    source: "demo_directory",
    sourceType: "partner_directory",
    sourceRef: "demo:orbit",
    providerOrg: "Orbit Spend Advisor",
    cardUrl: "https://directory.lumio.ai/partners/orbit",
    verticals: ["saas_procurement", "crm_software"],
    skills: ["compare_and_shortlist"],
    geo: ["SG", "AU"],
    authModes: ["oauth2"],
    acceptsSponsored: true,
    supportsDisclosure: true,
    supportsDeliveryReceipt: false,
    supportsPresentationReceipt: false,
    trustSeed: 0.74,
    leadScore: 0.76,
    discoveredAt: "2026-03-04T11:00:00.000Z",
    lastSeenAt: "2026-03-11T09:45:00.000Z",
    endpointUrl: "https://directory.lumio.ai/partners/orbit/opportunities",
    contactRef: "ops@orbitadvisor.ai",
    missingFields: ["supportsDeliveryReceipt", "supportsPresentationReceipt"],
    reachProxy: 0.72,
    monetizationReadiness: 0.75,
    verificationStatus: "reviewing",
    lastVerifiedAt: "2026-03-11T07:30:00.000Z",
    verificationOwner: "ops:carol",
    evidenceRef: "risk_demo_orbit_sla",
    assignedOwner: "ops:carol",
    notes: "In manual verification for APAC coverage demo.",
    dedupeKey: "orbit_spend_advisor_demo_directory",
    scoreBreakdown: { icpFit: 0.8, protocolFit: 0.72, reachFit: 0.72 },
  },
  {
    agentId: "lead_demo_lighthouse",
    dataOrigin: "seed",
    dataProvenance: "demo_seed",
    source: "demo_registry",
    sourceType: "public_registry",
    sourceRef: "demo:lighthouse",
    providerOrg: "Lighthouse Buying Copilot",
    cardUrl: "https://registry.lumio.ai/agents/lighthouse",
    verticals: ["crm_software", "sales_ops"],
    skills: ["compare_and_shortlist", "vendor_discovery"],
    geo: ["US", "EU"],
    authModes: ["oauth2"],
    acceptsSponsored: true,
    supportsDisclosure: true,
    supportsDeliveryReceipt: true,
    supportsPresentationReceipt: true,
    trustSeed: 0.79,
    leadScore: 0.8,
    discoveredAt: "2026-03-05T10:00:00.000Z",
    lastSeenAt: "2026-03-11T10:00:00.000Z",
    endpointUrl: "https://registry.lumio.ai/agents/lighthouse/opportunities",
    contactRef: "team@lighthousecopilot.ai",
    missingFields: [],
    reachProxy: 0.78,
    monetizationReadiness: 0.8,
    verificationStatus: "verified",
    lastVerifiedAt: "2026-03-11T09:15:00.000Z",
    verificationOwner: "ops:dana",
    evidenceRef: "asset_demo_northstar_case",
    assignedOwner: "ops:dana",
    notes: "Verified and queued for partner activation demo.",
    dedupeKey: "lighthouse_buying_copilot_demo_registry",
    scoreBreakdown: { icpFit: 0.82, protocolFit: 0.78, reachFit: 0.78 },
  },
];

const partners = [
  {
    partnerId: "partner_demo_northstar",
    agentLeadId: "lead_demo_northstar",
    dataProvenance: "demo_seed",
    providerOrg: "Northstar Procurement Desk",
    endpoint: "https://registry.lumio.ai/agents/northstar/opportunities",
    status: "active",
    supportedCategories: ["crm_software"],
    acceptsSponsored: true,
    supportsDisclosure: true,
    supportsDeliveryReceipt: true,
    supportsPresentationReceipt: true,
    lastVerifiedAt: "2026-03-11T08:00:00.000Z",
    verificationOwner: "ops:alice",
    evidenceRef: "asset_demo_northstar_case",
    trustScore: 0.9,
    authModes: ["oauth2", "api_key"],
    slaTier: "gold",
  },
  {
    partnerId: "partner_demo_summit",
    agentLeadId: "lead_demo_summit",
    dataProvenance: "demo_seed",
    providerOrg: "Summit RevOps Agent",
    endpoint: "https://directory.lumio.ai/partners/summit/opportunities",
    status: "active",
    supportedCategories: ["crm_software"],
    acceptsSponsored: true,
    supportsDisclosure: true,
    supportsDeliveryReceipt: true,
    supportsPresentationReceipt: true,
    lastVerifiedAt: "2026-03-11T08:10:00.000Z",
    verificationOwner: "ops:bob",
    evidenceRef: "asset_demo_northstar_case",
    trustScore: 0.84,
    authModes: ["oauth2"],
    slaTier: "gold",
  },
  {
    partnerId: "partner_demo_vector",
    agentLeadId: "lead_demo_vector",
    dataProvenance: "demo_seed",
    providerOrg: "Vector Workspace Agent",
    endpoint: "https://registry.lumio.ai/agents/vector/opportunities",
    status: "active",
    supportedCategories: ["crm_software", "workflow_automation"],
    acceptsSponsored: true,
    supportsDisclosure: true,
    supportsDeliveryReceipt: true,
    supportsPresentationReceipt: false,
    lastVerifiedAt: "2026-03-10T16:00:00.000Z",
    verificationOwner: "ops:alice",
    evidenceRef: "https://registry.lumio.ai/agents/vector/proof",
    trustScore: 0.83,
    authModes: ["oauth2", "api_key"],
    slaTier: "silver",
  },
  {
    partnerId: "partner_demo_orbit",
    agentLeadId: "lead_demo_orbit",
    dataProvenance: "demo_seed",
    providerOrg: "Orbit Spend Advisor",
    endpoint: "https://directory.lumio.ai/partners/orbit/opportunities",
    status: "reviewing",
    supportedCategories: ["crm_software"],
    acceptsSponsored: true,
    supportsDisclosure: true,
    supportsDeliveryReceipt: false,
    supportsPresentationReceipt: false,
    lastVerifiedAt: "2026-03-11T07:30:00.000Z",
    verificationOwner: "ops:carol",
    evidenceRef: "risk_demo_orbit_sla",
    trustScore: 0.74,
    authModes: ["oauth2"],
    slaTier: "silver",
  },
];

const campaigns = [
  {
    campaignId: "cmp_demo_hubflow",
    dataProvenance: "demo_seed",
    workspaceId: "workspace_demo",
    promotionPlanId: "trial",
    advertiser: "HubFlow",
    externalRef: null,
    sourceDocumentUrl: null,
    category: "crm_software",
    regions: ["UK", "EU", "US"],
    targetingPartnerIds: [],
    billingModel: "CPQR",
    payoutAmount: 140,
    currency: "USD",
    budget: 24000,
    status: "active",
    disclosureText: "Sponsored recommendation from HubFlow. Compensation may apply if shortlisted.",
    policyPass: true,
    minTrust: 0.65,
    linkBundle: {
      homepageUrl: "https://hubflow.ai",
      productDetailUrl: "https://hubflow.ai/security",
      proofUrl: "https://hubflow.ai/case-study",
      conversionUrl: "https://api.hubflow.ai/demo",
      contactUrl: null,
    },
    offer: {
      offerId: "offer_demo_hubflow",
      title: "HubFlow CRM for scaling B2B teams",
      description: "CRM focused on pipeline visibility, guided onboarding, and regional controls.",
      price: 499,
      currency: "USD",
      intendedFor: ["compare_and_shortlist", "vendor_discovery"],
      constraints: { company_size: "50-500" },
      claims: ["SOC 2 Type II", "Regional hosting", "14 day onboarding"],
      actionEndpoints: ["https://api.hubflow.ai/demo"],
      narrativeVariants: {
        rational: "Lower pipeline admin with guided sales workflows.",
        premium: "Enterprise CRM polish for RevOps-heavy teams.",
        simple: "A modern CRM with strong rollout support.",
      },
    },
    proofBundle: {
      proofBundleId: "proof_demo_hubflow",
      references: [
        { label: "Security overview", type: "doc", url: "https://hubflow.ai/security" },
        { label: "Case study", type: "case_study", url: "https://hubflow.ai/case-study" },
      ],
      updatedAt: "2026-03-03T00:00:00.000Z",
    },
  },
  {
    campaignId: "cmp_demo_signalstack",
    dataProvenance: "demo_seed",
    workspaceId: "workspace_demo",
    promotionPlanId: "trial",
    advertiser: "SignalStack",
    externalRef: null,
    sourceDocumentUrl: null,
    category: "crm_software",
    regions: ["UK", "EU", "US"],
    targetingPartnerIds: ["partner_demo_northstar", "partner_demo_summit"],
    billingModel: "CPA",
    payoutAmount: 980,
    currency: "USD",
    budget: 42000,
    status: "active",
    disclosureText: "Sponsored recommendation from SignalStack. Compensation may apply after a verified conversion.",
    policyPass: true,
    minTrust: 0.7,
    linkBundle: {
      homepageUrl: "https://signalstack.ai",
      productDetailUrl: "https://signalstack.ai/soc",
      proofUrl: "https://signalstack.ai/soc",
      conversionUrl: "https://api.signalstack.ai/trial",
      contactUrl: null,
    },
    offer: {
      offerId: "offer_demo_signalstack",
      title: "SignalStack for mid-market revenue teams",
      description: "CRM suite with territory planning, forecasting, and workflow automation.",
      price: 799,
      currency: "USD",
      intendedFor: ["compare_and_shortlist", "pricing_analysis"],
      constraints: { company_size: "100-1000" },
      claims: ["SOC 2 Type II", "Native ERP sync", "Dedicated success manager"],
      actionEndpoints: ["https://api.signalstack.ai/trial"],
      narrativeVariants: {
        rational: "High coverage for complex sales ops teams.",
        premium: "Enterprise-grade workflows without CRM sprawl.",
        simple: "A powerful CRM for teams that outgrew lightweight tools.",
      },
    },
    proofBundle: {
      proofBundleId: "proof_demo_signalstack",
      references: [
        { label: "Security certificate", type: "certificate", url: "https://signalstack.ai/soc" },
      ],
      updatedAt: "2026-03-04T00:00:00.000Z",
    },
  },
  {
    campaignId: "cmp_demo_northstar",
    dataProvenance: "demo_seed",
    workspaceId: "workspace_demo",
    promotionPlanId: "trial",
    advertiser: "Northstar CRM",
    externalRef: null,
    sourceDocumentUrl: null,
    category: "crm_software",
    regions: ["US", "EU"],
    targetingPartnerIds: ["partner_demo_vector", "partner_demo_northstar"],
    billingModel: "CPQR",
    payoutAmount: 180,
    currency: "USD",
    budget: 36000,
    status: "active",
    disclosureText: "Sponsored recommendation from Northstar CRM. Compensation may apply if shortlisted.",
    policyPass: true,
    minTrust: 0.68,
    linkBundle: {
      homepageUrl: "https://northstarcrm.ai",
      productDetailUrl: "https://northstarcrm.ai/migration",
      proofUrl: "https://northstarcrm.ai/customers",
      conversionUrl: "https://api.northstarcrm.ai/demo",
      contactUrl: null,
    },
    offer: {
      offerId: "offer_demo_northstar",
      title: "Northstar CRM for disciplined handoffs",
      description: "Revenue CRM for multi-team handoffs and territory governance.",
      price: 699,
      currency: "USD",
      intendedFor: ["compare_and_shortlist", "vendor_discovery"],
      constraints: { company_size: "75-700" },
      claims: ["SOC 2 Type II", "Role-based approvals", "Guided migration"],
      actionEndpoints: ["https://api.northstarcrm.ai/demo"],
      narrativeVariants: {
        rational: "Handoff discipline and governance without operational bloat.",
        premium: "A polished buyer journey for control-minded sales teams.",
        simple: "CRM built for cleaner handoffs and planning.",
      },
    },
    proofBundle: {
      proofBundleId: "proof_demo_northstar",
      references: [
        { label: "Migration guide", type: "doc", url: "https://northstarcrm.ai/migration" },
        { label: "Customer interview", type: "case_study", url: "https://northstarcrm.ai/customers" },
      ],
      updatedAt: "2026-03-05T00:00:00.000Z",
    },
  },
  {
    campaignId: "cmp_demo_vector",
    dataProvenance: "demo_seed",
    workspaceId: "workspace_demo",
    promotionPlanId: "trial",
    advertiser: "Vector Suite",
    externalRef: null,
    sourceDocumentUrl: null,
    category: "crm_software",
    regions: ["US", "CA"],
    targetingPartnerIds: ["partner_demo_vector"],
    billingModel: "CPQR",
    payoutAmount: 110,
    currency: "USD",
    budget: 18000,
    status: "active",
    disclosureText: "Sponsored recommendation from Vector Suite. Compensation may apply if shortlisted.",
    policyPass: true,
    minTrust: 0.66,
    linkBundle: {
      homepageUrl: "https://vectorworkspace.ai",
      productDetailUrl: "https://vectorworkspace.ai/pricing",
      proofUrl: "https://vectorworkspace.ai/pricing",
      conversionUrl: "https://api.vectorworkspace.ai/tour",
      contactUrl: null,
    },
    offer: {
      offerId: "offer_demo_vector",
      title: "Vector Suite for buyer enablement teams",
      description: "Workflow-heavy CRM with strong procurement collaboration features.",
      price: 459,
      currency: "USD",
      intendedFor: ["compare_and_shortlist"],
      constraints: { company_size: "25-250" },
      claims: ["Native approval trails", "Shared buying workspace"],
      actionEndpoints: ["https://api.vectorworkspace.ai/tour"],
      narrativeVariants: {
        rational: "Faster vendor comparisons with clean internal review trails.",
        premium: "A collaborative buyer workspace for teams scaling formal procurement.",
        simple: "CRM plus shared buying workflows.",
      },
    },
    proofBundle: {
      proofBundleId: "proof_demo_vector",
      references: [{ label: "Pricing overview", type: "doc", url: "https://vectorworkspace.ai/pricing" }],
      updatedAt: "2026-03-02T00:00:00.000Z",
    },
  },
  {
    campaignId: "cmp_demo_orbit",
    dataProvenance: "demo_seed",
    workspaceId: "workspace_demo",
    promotionPlanId: "trial",
    advertiser: "Orbit CRM",
    externalRef: null,
    sourceDocumentUrl: null,
    category: "crm_software",
    regions: ["SG", "AU"],
    targetingPartnerIds: ["partner_demo_orbit"],
    billingModel: "CPQR",
    payoutAmount: 90,
    currency: "USD",
    budget: 12000,
    status: "reviewing",
    disclosureText: "Sponsored recommendation from Orbit CRM. Compensation may apply if shortlisted.",
    policyPass: false,
    minTrust: 0.72,
    linkBundle: {
      homepageUrl: "https://orbitadvisor.ai",
      productDetailUrl: "https://orbitadvisor.ai/deploy",
      proofUrl: "https://orbitadvisor.ai/deploy",
      conversionUrl: "https://api.orbitadvisor.ai/demo",
      contactUrl: null,
    },
    offer: {
      offerId: "offer_demo_orbit",
      title: "Orbit CRM for APAC growth teams",
      description: "CRM with stronger reseller collaboration and lighter implementation overhead.",
      price: 389,
      currency: "USD",
      intendedFor: ["compare_and_shortlist"],
      constraints: { company_size: "20-200" },
      claims: ["Fast onboarding", "Regional support available"],
      actionEndpoints: ["https://api.orbitadvisor.ai/demo"],
      narrativeVariants: {
        rational: "A practical fit for teams standardising CRM without a full enterprise rollout.",
        premium: "A lighter APAC deployment with strong partner support.",
        simple: "Fast CRM rollout for regional growth teams.",
      },
    },
    proofBundle: {
      proofBundleId: "proof_demo_orbit",
      references: [{ label: "Deployment guide", type: "doc", url: "https://orbitadvisor.ai/deploy" }],
      updatedAt: "2026-02-28T00:00:00.000Z",
    },
  },
  {
    campaignId: "cmp_demo_velocity",
    dataProvenance: "demo_seed",
    workspaceId: "workspace_demo",
    promotionPlanId: "trial",
    advertiser: "VelocityCRM",
    externalRef: null,
    sourceDocumentUrl: null,
    category: "crm_software",
    regions: ["US"],
    targetingPartnerIds: [],
    billingModel: "CPA",
    payoutAmount: 2200,
    currency: "USD",
    budget: 22000,
    status: "rejected",
    disclosureText: "Sponsored recommendation from VelocityCRM.",
    policyPass: false,
    minTrust: 0.7,
    linkBundle: {
      homepageUrl: "https://velocitycrm.ai",
      productDetailUrl: "https://velocitycrm.ai/brochure",
      proofUrl: "https://velocitycrm.ai/brochure",
      conversionUrl: "https://api.velocitycrm.ai/signup",
      contactUrl: null,
    },
    offer: {
      offerId: "offer_demo_velocity",
      title: "VelocityCRM hyper-growth promise",
      description: "Aggressive performance-led CRM positioning for policy demo cases.",
      price: 299,
      currency: "USD",
      intendedFor: ["compare_and_shortlist"],
      constraints: { company_size: "10-150" },
      claims: ["100% guaranteed ROI in 7 days"],
      actionEndpoints: ["https://api.velocitycrm.ai/signup"],
      narrativeVariants: {
        rational: "Low-cost CRM positioned for short sales cycles.",
        premium: "Fast growth positioning with minimal setup.",
        simple: "CRM with aggressive performance messaging.",
      },
    },
    proofBundle: {
      proofBundleId: "proof_demo_velocity",
      references: [{ label: "Brochure", type: "doc", url: "https://velocitycrm.ai/brochure" }],
      updatedAt: "2026-03-01T00:00:00.000Z",
    },
  },
];

const verificationRecords = [
  {
    recordId: "verif_demo_northstar_active",
    leadId: "lead_demo_northstar",
    previousStatus: "verified",
    nextStatus: "active",
    checklist: { identity: true, auth: true, disclosure: true, sla: true, rateLimit: true },
    actorId: "ops:alice",
    comment: "Activated for enterprise procurement launch demo.",
    occurredAt: "2026-03-05T11:00:00.000Z",
  },
  {
    recordId: "verif_demo_summit_active",
    leadId: "lead_demo_summit",
    previousStatus: "verified",
    nextStatus: "active",
    checklist: { identity: true, auth: true, disclosure: true, sla: true, rateLimit: true },
    actorId: "ops:bob",
    comment: "Activated after revops review.",
    occurredAt: "2026-03-06T11:00:00.000Z",
  },
  {
    recordId: "verif_demo_vector_active",
    leadId: "lead_demo_vector",
    previousStatus: "verified",
    nextStatus: "active",
    checklist: { identity: true, auth: true, disclosure: true, sla: true, rateLimit: true },
    actorId: "ops:alice",
    comment: "Activated for North America workspace demo.",
    occurredAt: "2026-03-06T13:00:00.000Z",
  },
  {
    recordId: "verif_demo_orbit_reviewing",
    leadId: "lead_demo_orbit",
    previousStatus: "new",
    nextStatus: "reviewing",
    checklist: { identity: true, auth: true, disclosure: true, sla: false, rateLimit: true },
    actorId: "ops:carol",
    comment: "Waiting on SLA addendum before activation.",
    occurredAt: "2026-03-07T10:00:00.000Z",
  },
];

const evidenceAssets = [
  {
    assetId: "asset_demo_hubflow_pricing",
    dataProvenance: "demo_seed",
    campaignId: "cmp_demo_hubflow",
    type: "pricing",
    label: "HubFlow pricing sheet",
    url: "https://hubflow.ai/pricing",
    updatedAt: "2026-03-03T10:00:00.000Z",
    verifiedBy: "risk:irene",
    verificationNote: "Pricing verified against campaign copy.",
  },
  {
    assetId: "asset_demo_signalstack_soc",
    dataProvenance: "demo_seed",
    campaignId: "cmp_demo_signalstack",
    type: "certificate",
    label: "SignalStack SOC summary",
    url: "https://signalstack.ai/soc",
    updatedAt: "2026-03-02T10:00:00.000Z",
    verifiedBy: "risk:irene",
    verificationNote: "Security certificate confirmed.",
  },
  {
    assetId: "asset_demo_northstar_case",
    dataProvenance: "demo_seed",
    campaignId: "cmp_demo_northstar",
    type: "case_study",
    label: "Northstar migration case study",
    url: "https://northstarcrm.ai/case-study",
    updatedAt: "2026-03-05T10:00:00.000Z",
    verifiedBy: "ops:alice",
    verificationNote: "Approved for buyer enablement demo.",
  },
];

const riskCases = [
  {
    caseId: "risk_demo_velocity_rejected",
    dataProvenance: "demo_seed",
    entityType: "campaign",
    entityId: "cmp_demo_velocity",
    entityProvenance: "demo_seed",
    reasonType: "policy_violation",
    severity: "high",
    status: "resolved",
    openedAt: "2026-03-05T12:00:00.000Z",
    resolvedAt: "2026-03-06T12:00:00.000Z",
    ownerId: "risk:irene",
    note: "Rejected after high-risk claim language was confirmed.",
  },
  {
    caseId: "risk_demo_orbit_sla",
    dataProvenance: "demo_seed",
    entityType: "agent_lead",
    entityId: "lead_demo_orbit",
    entityProvenance: "demo_seed",
    reasonType: "policy_violation",
    severity: "medium",
    status: "open",
    openedAt: "2026-03-07T12:00:00.000Z",
    resolvedAt: null,
    ownerId: "risk:irene",
    note: "SLA evidence missing during APAC partner review.",
  },
];

const reputationRecords = [
  {
    recordId: "rep_demo_northstar_01",
    dataProvenance: "demo_seed",
    partnerId: "partner_demo_northstar",
    delta: 6,
    reasonType: "manual_adjustment",
    evidenceRefs: ["asset_demo_northstar_case"],
    disputeStatus: "none",
    occurredAt: "2026-03-05T12:00:00.000Z",
  },
  {
    recordId: "rep_demo_summit_01",
    dataProvenance: "demo_seed",
    partnerId: "partner_demo_summit",
    delta: -2,
    reasonType: "high_complaint",
    evidenceRefs: ["risk_demo_orbit_sla"],
    disputeStatus: "under_review",
    occurredAt: "2026-03-08T12:00:00.000Z",
  },
];

const appeals = [
  {
    appealId: "appeal_demo_summit_01",
    dataProvenance: "demo_seed",
    partnerId: "partner_demo_summit",
    targetRecordId: "rep_demo_summit_01",
    targetRecordProvenance: "demo_seed",
    status: "reviewing",
    statement: "Requesting a manual review of complaint weighting.",
    openedAt: "2026-03-09T15:00:00.000Z",
    decidedAt: null,
    decisionNote: null,
  },
];

export const buildDemoSeedData = (): SeedData => ({
  discoverySources,
  leads,
  partners,
  campaigns,
  verificationRecords,
  evidenceAssets,
  riskCases,
  reputationRecords,
  appeals,
  opcProfiles: [],
  revenueEvidence: [],
  verificationReviews: [],
  monthlyHealthSnapshots: [],
  channelProfiles: [],
  commercialExtensions: [],
  partnerOnboardingCases: [],
  capabilityVerificationSnapshots: [],
  partnerReserveAccounts: [],
  partnerReserveLedgerEntries: [],
} as unknown as SeedData);
