import type {
  AgentLead,
  AppealCase,
  Campaign,
  DiscoverySource,
  EvidenceAsset,
  PartnerAgent,
  ReputationRecord,
  RiskCase,
  VerificationRecord,
} from "./domain.js";

export type SeedData = {
  discoverySources: DiscoverySource[];
  leads: AgentLead[];
  partners: PartnerAgent[];
  campaigns: Campaign[];
  verificationRecords: VerificationRecord[];
  evidenceAssets: EvidenceAsset[];
  riskCases: RiskCase[];
  reputationRecords: ReputationRecord[];
  appeals: AppealCase[];
};

export const buildSeedData = (): SeedData => ({
  discoverySources: [
    {
      sourceId: "src_public_registry",
      sourceType: "public_registry",
      name: "MCP.so Servers",
      baseUrl: "https://mcp.so",
      seedUrls: [
        "https://mcp.so/servers",
      ],
      active: true,
      crawlPolicy: {
        rateLimit: 1,
        maxDepth: 1,
      },
      verticalHints: ["agent_orchestration", "developer_tools", "workflow_automation"],
      geoHints: ["US", "EU", "Global"],
      createdAt: "2026-03-01T08:00:00.000Z",
      updatedAt: "2026-03-11T08:00:00.000Z",
    },
    {
      sourceId: "src_partner_directory",
      sourceType: "partner_directory",
      name: "Glama MCP Servers",
      baseUrl: "https://glama.ai",
      seedUrls: [
        "https://glama.ai/mcp/servers",
      ],
      active: true,
      crawlPolicy: {
        rateLimit: 1,
        maxDepth: 1,
      },
      verticalHints: ["agent_orchestration", "developer_tools", "workflow_automation"],
      geoHints: ["US", "EU", "Global"],
      createdAt: "2026-03-01T08:30:00.000Z",
      updatedAt: "2026-03-11T08:30:00.000Z",
    },
  ],
  leads: [
    {
      agentId: "lead_crm_eu",
      dataOrigin: "seed",
      dataProvenance: "demo_seed",
      source: "registry",
      sourceType: "public_registry",
      sourceRef: "registry:procure-pilot",
      providerOrg: "ProcurePilot",
      cardUrl: "https://partners.example.com/procure-pilot",
      verticals: ["crm_software", "sales_ops"],
      skills: ["compare_and_shortlist", "vendor_discovery"],
      geo: ["UK", "EU"],
      authModes: ["oauth2", "api_key"],
      acceptsSponsored: true,
      supportsDisclosure: true,
      supportsDeliveryReceipt: true,
      supportsPresentationReceipt: true,
      trustSeed: 0.81,
      leadScore: 0.86,
      discoveredAt: "2026-03-01T09:00:00.000Z",
      lastSeenAt: "2026-03-11T09:00:00.000Z",
      endpointUrl: "https://partners.example.com/procure-pilot/opportunities",
      contactRef: "bizdev@procurepilot.example.com",
      missingFields: [],
      reachProxy: 0.84,
      monetizationReadiness: 0.82,
      verificationStatus: "active",
      lastVerifiedAt: "2026-03-10T12:00:00.000Z",
      verificationOwner: "ops:alice",
      evidenceRef: "https://partners.example.com/procure-pilot/verification",
      assignedOwner: "ops:alice",
      notes: "High-fit EU CRM procurement agent.",
      dedupeKey: "procurepilot_https_partners_example_com_procure_pilot_opportunities_public_registry",
      scoreBreakdown: {
        icpFit: 0.9,
        protocolFit: 0.82,
        reachFit: 0.84,
      },
    },
    {
      agentId: "lead_crm_cn",
      dataOrigin: "seed",
      dataProvenance: "demo_seed",
      source: "partner_directory",
      sourceType: "partner_directory",
      sourceRef: "partner-directory:growthdesk",
      providerOrg: "GrowthDesk Agent",
      cardUrl: "https://partners.example.com/growthdesk",
      verticals: ["crm_software", "revops"],
      skills: ["compare_and_shortlist", "pricing_analysis"],
      geo: ["CN", "SG"],
      authModes: ["oauth2"],
      acceptsSponsored: true,
      supportsDisclosure: true,
      supportsDeliveryReceipt: true,
      supportsPresentationReceipt: false,
      trustSeed: 0.78,
      leadScore: 0.82,
      discoveredAt: "2026-03-02T09:00:00.000Z",
      lastSeenAt: "2026-03-11T09:00:00.000Z",
      endpointUrl: "https://partners.example.com/growthdesk/opportunities",
      contactRef: "partners@growthdesk.example.com",
      missingFields: ["supportsPresentationReceipt"],
      reachProxy: 0.76,
      monetizationReadiness: 0.8,
      verificationStatus: "active",
      lastVerifiedAt: "2026-03-09T14:30:00.000Z",
      verificationOwner: "ops:bob",
      evidenceRef: "https://partners.example.com/growthdesk/verification",
      assignedOwner: "ops:bob",
      notes: "Strong APAC coverage and pricing analysis capability.",
      dedupeKey: "growthdesk_agent_https_partners_example_com_growthdesk_opportunities_partner_directory",
      scoreBreakdown: {
        icpFit: 0.82,
        protocolFit: 0.78,
        reachFit: 0.76,
      },
    },
  ],
  partners: [
    {
      partnerId: "partner_procure_pilot",
      agentLeadId: "lead_crm_eu",
      dataProvenance: "demo_seed",
      providerOrg: "ProcurePilot",
      endpoint: "https://partners.example.com/procure-pilot/opportunities",
      status: "active",
      supportedCategories: ["crm_software"],
      acceptsSponsored: true,
      supportsDisclosure: true,
      supportsDeliveryReceipt: true,
      supportsPresentationReceipt: true,
      lastVerifiedAt: "2026-03-10T12:00:00.000Z",
      verificationOwner: "ops:alice",
      evidenceRef: "https://partners.example.com/procure-pilot/verification",
      trustScore: 0.84,
      authModes: ["oauth2", "api_key"],
      slaTier: "gold",
    },
    {
      partnerId: "partner_growthdesk",
      agentLeadId: "lead_crm_cn",
      dataProvenance: "demo_seed",
      providerOrg: "GrowthDesk Agent",
      endpoint: "https://partners.example.com/growthdesk/opportunities",
      status: "active",
      supportedCategories: ["crm_software"],
      acceptsSponsored: true,
      supportsDisclosure: true,
      supportsDeliveryReceipt: true,
      supportsPresentationReceipt: false,
      lastVerifiedAt: "2026-03-09T14:30:00.000Z",
      verificationOwner: "ops:bob",
      evidenceRef: "https://partners.example.com/growthdesk/verification",
      trustScore: 0.8,
      authModes: ["oauth2"],
      slaTier: "silver",
    },
  ],
  campaigns: [
    {
      campaignId: "cmp_hubflow",
      dataProvenance: "demo_seed",
      workspaceId: "workspace_default",
      promotionPlanId: "trial",
      advertiser: "HubFlow",
      externalRef: null,
      sourceDocumentUrl: null,
      category: "crm_software",
      regions: ["UK", "EU", "CN"],
      targetingPartnerIds: [],
      billingModel: "CPQR",
      payoutAmount: 120,
      currency: "USD",
      budget: 12000,
      status: "active",
      disclosureText: "Sponsored recommendation from HubFlow. Compensation may apply if shortlisted.",
      policyPass: true,
      minTrust: 0.65,
      linkBundle: {
        homepageUrl: "https://hubflow.example.com",
        productDetailUrl: "https://hubflow.example.com/security",
        proofUrl: "https://hubflow.example.com/case-study",
        conversionUrl: "https://api.hubflow.example.com/demo",
        contactUrl: null,
      },
      offer: {
        offerId: "offer_hubflow",
        title: "HubFlow CRM for scaling B2B teams",
        description: "A CRM focused on pipeline visibility, AI assisted routing, and regional compliance.",
        price: 499,
        currency: "USD",
        intendedFor: ["compare_and_shortlist", "vendor_discovery"],
        constraints: {
          company_size: "50-500",
        },
        claims: ["ISO 27001 certified", "Regional data hosting available", "14 day guided onboarding"],
        actionEndpoints: ["https://api.hubflow.example.com/demo"],
        narrativeVariants: {
          rational: "Lower admin overhead with structured pipeline automation.",
          premium: "A polished buying experience for RevOps-heavy sales organizations.",
          simple: "Modern CRM with strong automation and regional hosting.",
        },
      },
      proofBundle: {
        proofBundleId: "proof_hubflow",
        references: [
          {
            label: "Security overview",
            type: "doc",
            url: "https://hubflow.example.com/security",
          },
          {
            label: "Customer case study",
            type: "case_study",
            url: "https://hubflow.example.com/case-study",
          },
        ],
        updatedAt: "2026-03-01T00:00:00.000Z",
      },
    },
    {
      campaignId: "cmp_signalstack",
      dataProvenance: "demo_seed",
      workspaceId: "workspace_default",
      promotionPlanId: "trial",
      advertiser: "SignalStack",
      externalRef: null,
      sourceDocumentUrl: null,
      category: "crm_software",
      regions: ["UK", "EU"],
      targetingPartnerIds: ["partner_procure_pilot"],
      billingModel: "CPA",
      payoutAmount: 900,
      currency: "USD",
      budget: 30000,
      status: "active",
      disclosureText: "Sponsored recommendation from SignalStack. Compensation may apply after a verified conversion.",
      policyPass: true,
      minTrust: 0.7,
      linkBundle: {
        homepageUrl: "https://signalstack.example.com",
        productDetailUrl: "https://signalstack.example.com/soc",
        proofUrl: "https://signalstack.example.com/soc",
        conversionUrl: "https://api.signalstack.example.com/trial",
        contactUrl: null,
      },
      offer: {
        offerId: "offer_signalstack",
        title: "SignalStack for mid-market revenue teams",
        description: "CRM suite with territory planning, AI forecasting, and deeper workflow controls.",
        price: 799,
        currency: "USD",
        intendedFor: ["compare_and_shortlist", "pricing_analysis"],
        constraints: {
          company_size: "100-1000",
        },
        claims: ["SOC 2 Type II", "Dedicated success manager", "Native ERP sync"],
        actionEndpoints: ["https://api.signalstack.example.com/trial"],
        narrativeVariants: {
          rational: "High coverage for complex sales ops teams with strong auditability.",
          premium: "Enterprise-grade workflows without the typical CRM bloat.",
          simple: "Powerful CRM for teams that outgrew lightweight tools.",
        },
      },
      proofBundle: {
        proofBundleId: "proof_signalstack",
        references: [
          {
            label: "SOC report summary",
            type: "certificate",
            url: "https://signalstack.example.com/soc",
          },
        ],
        updatedAt: "2026-02-15T00:00:00.000Z",
      },
    },
  ],
  verificationRecords: [
    {
      recordId: "verif_procurepilot_active",
      leadId: "lead_crm_eu",
      previousStatus: "verified",
      nextStatus: "active",
      checklist: {
        identity: true,
        auth: true,
        disclosure: true,
        sla: true,
        rateLimit: true,
      },
      actorId: "ops:alice",
      comment: "Activated after endpoint and disclosure review.",
      occurredAt: "2026-03-05T11:00:00.000Z",
    },
    {
      recordId: "verif_growthdesk_active",
      leadId: "lead_crm_cn",
      previousStatus: "verified",
      nextStatus: "active",
      checklist: {
        identity: true,
        auth: true,
        disclosure: true,
        sla: true,
        rateLimit: true,
      },
      actorId: "ops:bob",
      comment: "Activated after APAC partner review.",
      occurredAt: "2026-03-06T11:00:00.000Z",
    },
  ],
  evidenceAssets: [
    {
      assetId: "asset_hubflow_pricing",
      dataProvenance: "demo_seed",
      campaignId: "cmp_hubflow",
      type: "pricing",
      label: "HubFlow pricing sheet",
      url: "https://hubflow.example.com/pricing",
      updatedAt: "2026-03-03T10:00:00.000Z",
      verifiedBy: "risk:irene",
      verificationNote: "Pricing verified against campaign copy.",
    },
    {
      assetId: "asset_signalstack_soc",
      dataProvenance: "demo_seed",
      campaignId: "cmp_signalstack",
      type: "certificate",
      label: "SignalStack SOC summary",
      url: "https://signalstack.example.com/soc",
      updatedAt: "2026-03-02T10:00:00.000Z",
      verifiedBy: "risk:irene",
      verificationNote: "Security certificate confirmed.",
    },
  ],
  riskCases: [
    {
      caseId: "risk_signalstack_review",
      dataProvenance: "demo_seed",
      entityType: "campaign",
      entityId: "cmp_signalstack",
      entityProvenance: "demo_seed",
      reasonType: "policy_violation",
      severity: "medium",
      status: "resolved",
      openedAt: "2026-03-04T12:00:00.000Z",
      resolvedAt: "2026-03-05T12:00:00.000Z",
      ownerId: "risk:irene",
      note: "Resolved after additional SOC proof was added.",
    },
  ],
  reputationRecords: [
    {
      recordId: "rep_partner_procurepilot_01",
      dataProvenance: "demo_seed",
      partnerId: "partner_procure_pilot",
      delta: 4,
      reasonType: "manual_adjustment",
      evidenceRefs: [],
      disputeStatus: "none",
      occurredAt: "2026-03-05T12:00:00.000Z",
    },
  ],
  appeals: [
    {
      appealId: "appeal_procurepilot_01",
      dataProvenance: "demo_seed",
      partnerId: "partner_procure_pilot",
      targetRecordId: "rep_partner_procurepilot_01",
      targetRecordProvenance: "demo_seed",
      status: "approved",
      statement: "Requesting review of manual adjustment rationale.",
      openedAt: "2026-03-06T15:00:00.000Z",
      decidedAt: "2026-03-07T15:00:00.000Z",
      decisionNote: "Clarified and approved by risk team.",
    },
  ],
} as unknown as SeedData);
